version: "3.8"
services:
  webapp:
    build:
      context: .
      dockerfile: docker-webscraper.yml
    container_name: webscrape-container
    volumes:
     - /usr/src/logs:/usr/src/logs
    ports:
     - "3000:3000"
    depends_on:
     - mongo
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
    - "27017:27017"