version: "3.8"
services:
  webapp:
    build:
      context: .
      dockerfile: docker-webscraper.yml
    container_name: webscrape-container
    volumes:
     - /srv/cherry-pick/logs:/srv/Cherry-Pick/logs
    ports:
     - "3000:3000"
    depends_on:
     - mongo
  mongo:
    image: mongo
    container_name: mongo-container